/*
Copyright (C) 2025, Microchip Technology Inc., and its subsidiaries. All rights reserved.

The software and documentation is provided by microchip and its contributors
"as is" and any express, implied or statutory warranties, including, but not
limited to, the implied warranties of merchantability, fitness for a particular
purpose and non-infringement of third party intellectual property rights are
disclaimed to the fullest extent permitted by law. In no event shall microchip
or its contributors be liable for any direct, indirect, incidental, special,
exemplary, or consequential damages (including, but not limited to, procurement
of substitute goods or services; loss of use, data, or profits; or business
interruption) however caused and on any theory of liability, whether in contract,
strict liability, or tort (including negligence or otherwise) arising in any way
out of the use of the software and documentation, even if advised of the
possibility of such damage.

Except as expressly permitted hereunder and subject to the applicable license terms
for any third-party software incorporated in the software and any applicable open
source software license terms, no license or other rights, whether express or
implied, are granted under any patent or other intellectual property rights of
Microchip or any third party.
*/

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************
#include "definitions.h"
#include "atm90e32_regs.h"

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************

static const ATM90EXX_REG_INFO CACHE_ALIGN atm90exxRegsInfo[] = {   
    // ATM90EXX_REGS_CONTROL
    // Default Value                    , Register Address  , Refresh Flas Config  , Register Name
    { ((uint16_t)(0x0))                 , INVALID_ADDR      , CONFIG_FLAG_ALL      , "USCALE   " },
    { ((uint16_t)(0x0))                 , INVALID_ADDR      , CONFIG_FLAG_ALL      , "ISCALE   " },    
    { 0x0001                            , INVALID_ADDR      , CONFIG_FLAG_ALL      , "PWRMODE  " },
    //{ SOFTRESET_DEFAULT_Val             , SOFTRESET_ADDR    , CONFIG_FLAG_NONE     , "SOFTRST " },
    { METEREN_DEFAULT_Val               , METEREN_ADDR      , CONFIG_FLAG_CFGSTART , "METEREN  " },
    { CHANNELMAPI_DEFAULT_Val           , CHANNELMAPI_ADDR  , CONFIG_FLAG_CFGSTART , "CHANMAPI " },
    { CHANNELMAPU_DEFAULT_Val           , CHANNELMAPU_ADDR  , CONFIG_FLAG_CFGSTART , "CHANMAPU " },
    { SAGPEAKDETCFG_DEFAULT_Val         , SAGPEAKDETCFG_ADDR, CONFIG_FLAG_CFGSTART , "SAGPEAK  " },
    { ZXCONFIG_DEFAULT_Val              , ZXCONFIG_ADDR     , CONFIG_FLAG_CFGSTART , "ZXCONFIG " },
//    { PMPWRCTRL_DEFAULT_Val             , PMPWRCTRL_ADDR    , CONFIG_FLAG_CFGSTART , "PMPWCTRL" },    
    { IRQ0MERGECFG_DEFAULT_Val          , IRQ0MERGECFG_ADDR , CONFIG_FLAG_CFGSTART , "IRQ0MRG  " },
    { MMODE0_DEFAULT_Val                , MMODE0_ADDR       , CONFIG_FLAG_CFGSTART , "MMODE0   " },
    { MMODE1_DEFAULT_Val                , MMODE1_ADDR       , CONFIG_FLAG_CFGSTART , "MMODE1   " },
    { CFGREGACCEN_DEFAULT_Val           , CFGREGACCEN_ADDR  , CONFIG_FLAG_NONE     , "CFGREGACC" },
    { EMMINTEN0_DEFAULT_Val             , EMMINTEN0_ADDR    , CONFIG_FLAG_NONE     , "EMINTEN0 " },
    { EMMINTEN1_DEFAULT_Val             , EMMINTEN1_ADDR    , CONFIG_FLAG_NONE     , "EMINTEN1 " },
    { CRCDIGEST_DEFAULT_Val             , CRCDIGEST_ADDR    , CONFIG_FLAG_NONE     , "CRCDIG   " },
    // ATM90EXX_REGS_THRESHOLDS
    { SAGTH_DEFAULT_Val                 , SAGTH_ADDR        , CONFIG_FLAG_CFGSTART , "SAGTH    " },
    { OVTH_DEFAULT_Val                  , OVTH_ADDR         , CONFIG_FLAG_CFGSTART , "OVTH     " },
    { PHASELOSSTH_DEFAULT_Val           , PHASELOSSTH_ADDR  , CONFIG_FLAG_CFGSTART , "PHLOSSTH " },
    { INWARNTH_DEFAULT_Val              , INWARNTH_ADDR     , CONFIG_FLAG_CFGSTART , "INWARNTH " },
    { OITH_DEFAULT_Val                  , OITH_ADDR         , CONFIG_FLAG_CFGSTART , "OITH     " },
    { FREQLOTH_DEFAULT_Val              , FREQLOTH_ADDR     , CONFIG_FLAG_CFGSTART , "FREQLOTH " },
    { FREQHITH_DEFAULT_Val              , FREQHITH_ADDR     , CONFIG_FLAG_CFGSTART , "FREQHIGH " },
    { PSTARTTH_DEFAULT_Val              , PSTARTTH_ADDR     , CONFIG_FLAG_CFGSTART , "PSTARTTH " },
    { QSTARTTH_DEFAULT_Val              , QSTARTTH_ADDR     , CONFIG_FLAG_CFGSTART , "QSTARTTH " },
    { SSTARTTH_DEFAULT_Val              , SSTARTTH_ADDR     , CONFIG_FLAG_CFGSTART , "SSTARTTH " },
    { PPHASETH_DEFAULT_Val              , PPHASETH_ADDR     , CONFIG_FLAG_CFGSTART , "PPHASETH " },
    { QPHASETH_DEFAULT_Val              , QPHASETH_ADDR     , CONFIG_FLAG_CFGSTART , "QPHASETH " },
    { SPHASETH_DEFAULT_Val              , SPHASETH_ADDR     , CONFIG_FLAG_CFGSTART , "SPHASETH " },
//    { 0x0000                            , DETECTCTRL_ADDR   , CONFIG_FLAG_CFGSTART , "DETCTRL  " },
//    { 0x0000                            , DETECTTH1_ADDR    , CONFIG_FLAG_CFGSTART , "DETTH1   " },
//    { 0x0000                            , DETECTTH2_ADDR    , CONFIG_FLAG_CFGSTART , "DETTH2   " },
//    { 0x0000                            , DETECTTH3_ADDR    , CONFIG_FLAG_CFGSTART , "DETTH3   " },
//    { 0x0000                            , IDCOFFSETA_ADDR   , CONFIG_FLAG_CFGSTART , "IDCOFFA  " },
//    { 0x0000                            , IDCOFFSETB_ADDR   , CONFIG_FLAG_CFGSTART , "IDCOFFB  " },
//    { 0x0000                            , IDCOFFSETC_ADDR   , CONFIG_FLAG_CFGSTART , "IDCOFFC  " },
//    { 0x0000                            , UDCOFFSETA_ADDR   , CONFIG_FLAG_CFGSTART , "UDCOFFA  " },
//    { 0x0000                            , UDCOFFSETB_ADDR   , CONFIG_FLAG_CFGSTART , "UDCOFFB  " },
//    { 0x0000                            , UDCOFFSETC_ADDR   , CONFIG_FLAG_CFGSTART , "UDCOFFC  " },
//    { 0x0000                            , UGAINTAB_ADDR     , CONFIG_FLAG_CFGSTART , "UGAINTAB " },
//    { 0x0000                            , UGAINTC_ADDR      , CONFIG_FLAG_CFGSTART , "UGAINTC  " },
//    { 0x0000                            , PHIFREQCOMP_ADDR  , CONFIG_FLAG_CFGSTART , "PHIFREQC " },
//    { 0x0000                            , LOGIRMS0_ADDR     , CONFIG_FLAG_CFGSTART , "LOGIRMS0 " },
//    { 0x0000                            , LOGIRMS1_ADDR     , CONFIG_FLAG_CFGSTART , "LOGIRMS1 " },
//    { 0x1388                            , F0_ADDR           , CONFIG_FLAG_CFGSTART , "F0       " },
//    { 0x0019                            , T0_ADDR           , CONFIG_FLAG_CFGSTART , "T0       " },    
//    { 0x0000                            , PHIAIRMS01_ADDR   , CONFIG_FLAG_CFGSTART , "PHIAI01  " },
//    { 0x0000                            , PHIAIRMS2_ADDR    , CONFIG_FLAG_CFGSTART , "PHIAI2   " },
//    { 0x0000                            , GAINAIRMS01_ADDR  , CONFIG_FLAG_CFGSTART , "GAINAI01 " },
//    { 0x0000                            , GAINAIRMS2_ADDR   , CONFIG_FLAG_CFGSTART , "GAINAI2  " },
//    { 0x0000                            , PHIBIRMS01_ADDR   , CONFIG_FLAG_CFGSTART , "PHIBI01  " },
//    { 0x0000                            , PHIBIRMS2_ADDR    , CONFIG_FLAG_CFGSTART , "PHIBI2   " },
//    { 0x0000                            , GAINBIRMS01_ADDR  , CONFIG_FLAG_CFGSTART , "GAINBI01 " },
//    { 0x0000                            , GAINBIRMS2_ADDR   , CONFIG_FLAG_CFGSTART , "GAINBI2  " },
//    { 0x0000                            , PHICIRMS01_ADDR   , CONFIG_FLAG_CFGSTART , "PHICI01  " },
//    { 0x0000                            , PHICIRMS2_ADDR    , CONFIG_FLAG_CFGSTART , "PHICI2   " },
//    { 0x0000                            , GAINCIRMS01_ADDR  , CONFIG_FLAG_CFGSTART , "GAINCI01 " },
//    { 0x0000                            , GAINCIRMS2_ADDR   , CONFIG_FLAG_CFGSTART , "GAINCI2  " },
    // ATM90EXX_REGS_CAL_MEAS
    { UGAINA_GAIN_DEFAULT_Val           , UGAINA_ADDR       , CONFIG_FLAG_CFGSTART , "UGAINA   " },
    { IGAINA_GAIN_DEFAULT_Val           , IGAINA_ADDR       , CONFIG_FLAG_CFGSTART , "IGAINA   " },
    { UOFFSETA_OFFSET_DEFAULT_Val       , UOFFSETA_ADDR     , CONFIG_FLAG_CFGSTART , "UOFFSETA " },
    { IOFFSETA_OFFSET_DEFAULT_Val       , IOFFSETA_ADDR     , CONFIG_FLAG_CFGSTART , "IOFFSETA " },
    { UGAINB_GAIN_DEFAULT_Val           , UGAINB_ADDR       , CONFIG_FLAG_CFGSTART , "UGAINB   " },
    { IGAINB_GAIN_DEFAULT_Val           , IGAINB_ADDR       , CONFIG_FLAG_CFGSTART , "IGAINB   " },
    { UOFFSETB_OFFSET_DEFAULT_Val       , UOFFSETB_ADDR     , CONFIG_FLAG_CFGSTART , "UOFFSETB " },
    { IOFFSETB_OFFSET_DEFAULT_Val       , IOFFSETB_ADDR     , CONFIG_FLAG_CFGSTART , "IOFFSETB " },
    { UGAINC_GAIN_DEFAULT_Val           , UGAINC_ADDR       , CONFIG_FLAG_CFGSTART , "UGAINC   " },
    { IGAINC_GAIN_DEFAULT_Val           , IGAINC_ADDR       , CONFIG_FLAG_CFGSTART , "IGAINC   " },
    { UOFFSETC_OFFSET_DEFAULT_Val       , UOFFSETC_ADDR     , CONFIG_FLAG_CFGSTART , "UOFFSETC " },
    { IOFFSETC_OFFSET_DEFAULT_Val       , IOFFSETC_ADDR     , CONFIG_FLAG_CFGSTART , "IOFFSETC " },
    // ATM90EXX_REGS_CAL_MET
    { 3200                              , INVALID_ADDR      , CONFIG_FLAG_CALSTART , "METER C  " },
    { PLCONSTH_DEFAULT_Val              , PLCONSTH_ADDR     , CONFIG_FLAG_CFGSTART , "PLCONSTH " },
    { PLCONSTL_DEFAULT_Val              , PLCONSTL_ADDR     , CONFIG_FLAG_CFGSTART , "PLCONSTL " },
    { POFFSETA_OFFSET_DEFAULT_Val       , POFFSETA_ADDR     , CONFIG_FLAG_CFGSTART , "POFFSETA " },
    { QOFFSETA_OFFSET_DEFAULT_Val       , QOFFSETA_ADDR     , CONFIG_FLAG_CFGSTART , "QOFFSETA " },
    { POFFSETB_OFFSET_DEFAULT_Val       , POFFSETB_ADDR     , CONFIG_FLAG_CFGSTART , "POFFSETB " },
    { QOFFSETB_OFFSET_DEFAULT_Val       , QOFFSETB_ADDR     , CONFIG_FLAG_CFGSTART , "QOFFSETB " },
    { POFFSETC_OFFSET_DEFAULT_Val       , POFFSETC_ADDR     , CONFIG_FLAG_CFGSTART , "POFFSETC " },
    { QOFFSETC_OFFSET_DEFAULT_Val       , QOFFSETC_ADDR     , CONFIG_FLAG_CFGSTART , "QOFFSETC " },
    { PQGAINA_GAIN_DEFAULT_Val          , PQGAINA_ADDR      , CONFIG_FLAG_CFGSTART , "PQGAINA  " },
    { PQGAINB_GAIN_DEFAULT_Val          , PQGAINB_ADDR      , CONFIG_FLAG_CFGSTART , "PQGAINB  " },
    { PQGAINC_GAIN_DEFAULT_Val          , PQGAINC_ADDR      , CONFIG_FLAG_CFGSTART , "PQGAINC  " },
    { PHIA_DEFAULT_Val                  , PHIA_ADDR         , CONFIG_FLAG_CFGSTART , "PHIA     " },
    { PHIB_DEFAULT_Val                  , PHIB_ADDR         , CONFIG_FLAG_CFGSTART , "PHIB     " },
    { PHIC_DEFAULT_Val                  , PHIC_ADDR         , CONFIG_FLAG_CFGSTART , "PHIC     " },
    { POFFSETAF_OFFSET_DEFAULT_Val      , POFFSETAF_ADDR    , CONFIG_FLAG_CFGSTART , "POFFSETAF" },
    { POFFSETBF_OFFSET_DEFAULT_Val      , POFFSETBF_ADDR    , CONFIG_FLAG_CFGSTART , "POFFSETBF" },
    { POFFSETCF_OFFSET_DEFAULT_Val      , POFFSETCF_ADDR    , CONFIG_FLAG_CFGSTART , "POFFSETCF" },
    { PGAINAF_GAIN_DEFAULT_Val          , PGAINAF_ADDR      , CONFIG_FLAG_CFGSTART , "PGAINAF  " },
    { PGAINBF_GAIN_DEFAULT_Val          , PGAINBF_ADDR      , CONFIG_FLAG_CFGSTART , "PGAINBF  " },
    { PGAINCF_GAIN_DEFAULT_Val          , PGAINCF_ADDR      , CONFIG_FLAG_CFGSTART , "PGAINCF  " },
    // ATM90EXX_REGS_STATUS
    { EMMSTATE0_DEFAULT_Val             , EMMSTATE0_ADDR    , CONFIG_FLAG_NONE     , "EMST0    " },
    { EMMSTATE1_DEFAULT_Val             , EMMSTATE1_ADDR    , CONFIG_FLAG_NONE     , "EMST1    " },
    { EMMINTSTATE0_DEFAULT_Val          , EMMINTSTATE0_ADDR , CONFIG_FLAG_NONE     , "EMINTST0 " },
    { EMMINTSTATE1_DEFAULT_Val          , EMMINTSTATE1_ADDR , CONFIG_FLAG_NONE     , "EMINTST1 " },
    { LASTSPIDATA_DEFAULT_Val           , LASTSPIDATA_ADDR  , CONFIG_FLAG_NONE     , "LASTSPI  " },
    { CRCERRSTATUS_DEFAULT_Val          , CRCERRSTATUS_ADDR , CONFIG_FLAG_NONE     , "CRCERRST " },
    // ATM90EXX_REGS_MEAS
    { PMEAN_DEFAULT_Val                 , PMEANT_ADDR       , CONFIG_FLAG_NONE     , "PMEAN    " },
    { PMEAN_DEFAULT_Val                 , PMEANA_ADDR       , CONFIG_FLAG_NONE     , "PMEANA   " },
    { PMEAN_DEFAULT_Val                 , PMEANB_ADDR       , CONFIG_FLAG_NONE     , "PMEANB   " },
    { PMEAN_DEFAULT_Val                 , PMEANC_ADDR       , CONFIG_FLAG_NONE     , "PMEANC   " },
    { QMEAN_DEFAULT_Val                 , QMEANT_ADDR       , CONFIG_FLAG_NONE     , "QMEAN    " },
    { QMEAN_DEFAULT_Val                 , QMEANA_ADDR       , CONFIG_FLAG_NONE     , "QMEANA   " },
    { QMEAN_DEFAULT_Val                 , QMEANB_ADDR       , CONFIG_FLAG_NONE     , "QMEANB   " },
    { QMEAN_DEFAULT_Val                 , QMEANC_ADDR       , CONFIG_FLAG_NONE     , "QMEANC   " },
    { SMEAN_DEFAULT_Val                 , SAMEANT_ADDR      , CONFIG_FLAG_NONE     , "SMEAN    " },
    { SMEAN_DEFAULT_Val                 , SMEANA_ADDR       , CONFIG_FLAG_NONE     , "SMEANA   " },
    { SMEAN_DEFAULT_Val                 , SMEANB_ADDR       , CONFIG_FLAG_NONE     , "SMEANB   " },
    { SMEAN_DEFAULT_Val                 , SMEANC_ADDR       , CONFIG_FLAG_NONE     , "SMEANC   " },
    { PFMEAN_DEFAULT_Val                , PFMEANT_ADDR      , CONFIG_FLAG_NONE     , "PFMEAN   " },
    { PFMEAN_DEFAULT_Val                , PFMEANA_ADDR      , CONFIG_FLAG_NONE     , "PFMEANA  " },
    { PFMEAN_DEFAULT_Val                , PFMEANB_ADDR      , CONFIG_FLAG_NONE     , "PFMEANB  " },
    { PFMEAN_DEFAULT_Val                , PFMEANC_ADDR      , CONFIG_FLAG_NONE     , "PFMEANC  " },
    { PMEAN_DEFAULT_Val                 , PMEANTLSB_ADDR    , CONFIG_FLAG_NONE     , "PMEANLSB " },
    { PMEAN_DEFAULT_Val                 , PMEANALSB_ADDR    , CONFIG_FLAG_NONE     , "PMEANALSB" },
    { PMEAN_DEFAULT_Val                 , PMEANBLSB_ADDR    , CONFIG_FLAG_NONE     , "PMEANBLSB" },
    { PMEAN_DEFAULT_Val                 , PMEANCLSB_ADDR    , CONFIG_FLAG_NONE     , "PMEANCLSB" },
    { QMEAN_DEFAULT_Val                 , QMEANTLSB_ADDR    , CONFIG_FLAG_NONE     , "QMEANLSB " },
    { QMEAN_DEFAULT_Val                 , QMEANALSB_ADDR    , CONFIG_FLAG_NONE     , "QMEANALSB" },
    { QMEAN_DEFAULT_Val                 , QMEANBLSB_ADDR    , CONFIG_FLAG_NONE     , "QMEANBLSB" },
    { QMEAN_DEFAULT_Val                 , QMEANCLSB_ADDR    , CONFIG_FLAG_NONE     , "QMEANCLSB" },
    { SMEAN_DEFAULT_Val                 , SAMEANTLSB_ADDR   , CONFIG_FLAG_NONE     , "SMEANLSB " },
    { SMEAN_DEFAULT_Val                 , SMEANALSB_ADDR    , CONFIG_FLAG_NONE     , "SMEANALSB" },
    { SMEAN_DEFAULT_Val                 , SMEANBLSB_ADDR    , CONFIG_FLAG_NONE     , "SMEANBLSB" },
    { SMEAN_DEFAULT_Val                 , SMEANCLSB_ADDR    , CONFIG_FLAG_NONE     , "SMEANCLSB" },
    { PMEAN_DEFAULT_Val                 , PMEANTF_ADDR      , CONFIG_FLAG_NONE     , "PMEANF   " },
    { PMEAN_DEFAULT_Val                 , PMEANAF_ADDR      , CONFIG_FLAG_NONE     , "PMEANAF  " },
    { PMEAN_DEFAULT_Val                 , PMEANBF_ADDR      , CONFIG_FLAG_NONE     , "PMEANBF  " },
    { PMEAN_DEFAULT_Val                 , PMEANCF_ADDR      , CONFIG_FLAG_NONE     , "PMEANCF  " },
    { PMEAN_DEFAULT_Val                 , PMEANTH_ADDR      , CONFIG_FLAG_NONE     , "PMEANH   " },
    { PMEAN_DEFAULT_Val                 , PMEANAH_ADDR      , CONFIG_FLAG_NONE     , "PMEANAH  " },
    { PMEAN_DEFAULT_Val                 , PMEANBH_ADDR      , CONFIG_FLAG_NONE     , "PMEANBH  " },
    { PMEAN_DEFAULT_Val                 , PMEANCH_ADDR      , CONFIG_FLAG_NONE     , "PMEANCH  " },
    { URMS_DEFAULT_Val                  , URMSA_ADDR        , CONFIG_FLAG_NONE     , "URMSA    " },
    { URMS_DEFAULT_Val                  , URMSB_ADDR        , CONFIG_FLAG_NONE     , "URMSB    " },
    { URMS_DEFAULT_Val                  , URMSC_ADDR        , CONFIG_FLAG_NONE     , "URMSC    " },
    { IRMS_DEFAULT_Val                  , IRMSN_ADDR        , CONFIG_FLAG_NONE     , "IRMSN    " },
    { IRMS_DEFAULT_Val                  , IRMSA_ADDR        , CONFIG_FLAG_NONE     , "IRMSA    " },
    { IRMS_DEFAULT_Val                  , IRMSB_ADDR        , CONFIG_FLAG_NONE     , "IRMSB    " },
    { IRMS_DEFAULT_Val                  , IRMSC_ADDR        , CONFIG_FLAG_NONE     , "IRMSC    " },
    { PMEAN_DEFAULT_Val                 , PMEANTFLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANFLSB" },
    { PMEAN_DEFAULT_Val                 , PMEANAFLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANAFLS" },
    { PMEAN_DEFAULT_Val                 , PMEANBFLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANBFLS" },
    { PMEAN_DEFAULT_Val                 , PMEANCFLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANCFLS" },
    { PMEAN_DEFAULT_Val                 , PMEANTHLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANHLSB" },
    { PMEAN_DEFAULT_Val                 , PMEANAHLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANAHLS" },
    { PMEAN_DEFAULT_Val                 , PMEANBHLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANBHLS" },
    { PMEAN_DEFAULT_Val                 , PMEANCHLSB_ADDR   , CONFIG_FLAG_NONE     , "PMEANCHLS" },
    { URMS_DEFAULT_Val                  , URMSALSB_ADDR     , CONFIG_FLAG_NONE     , "URMSALSB " },
    { URMS_DEFAULT_Val                  , URMSBLSB_ADDR     , CONFIG_FLAG_NONE     , "URMSBLSB " },
    { URMS_DEFAULT_Val                  , URMSCLSB_ADDR     , CONFIG_FLAG_NONE     , "URMSCLSB " },
    { IRMS_DEFAULT_Val                  , IRMSALSB_ADDR     , CONFIG_FLAG_NONE     , "IRMSALSB " },
    { IRMS_DEFAULT_Val                  , IRMSBLSB_ADDR     , CONFIG_FLAG_NONE     , "IRMSBLSB " },
    { IRMS_DEFAULT_Val                  , IRMSCLSB_ADDR     , CONFIG_FLAG_NONE     , "IRMSCLSB " },
    { UPEAK_DEFAULT_Val                 , UPEAKA_ADDR       , CONFIG_FLAG_NONE     , "UPEAKA   " },
    { UPEAK_DEFAULT_Val                 , UPEAKB_ADDR       , CONFIG_FLAG_NONE     , "UPEAKB   " },
    { UPEAK_DEFAULT_Val                 , UPEAKC_ADDR       , CONFIG_FLAG_NONE     , "UPEAKC   " },
    { IPEAK_DEFAULT_Val                 , IPEAKA_ADDR       , CONFIG_FLAG_NONE     , "IPEAKA   " },
    { IPEAK_DEFAULT_Val                 , IPEAKB_ADDR       , CONFIG_FLAG_NONE     , "IPEAKB   " },
    { IPEAK_DEFAULT_Val                 , IPEAKC_ADDR       , CONFIG_FLAG_NONE     , "IPEAKC   " },
    { FREQ_DEFAULT_Val                  , FREQ_ADDR         , CONFIG_FLAG_NONE     , "FREQ     " },
    { ANGLE_DEFAULT_Val                 , PANGLEA_ADDR      , CONFIG_FLAG_NONE     , "PANGLEA  " },
    { ANGLE_DEFAULT_Val                 , PANGLEB_ADDR      , CONFIG_FLAG_NONE     , "PANGLEB  " },
    { ANGLE_DEFAULT_Val                 , PANGLEC_ADDR      , CONFIG_FLAG_NONE     , "PANGLEC  " },
    { TEMP_DEFAULT_Val                  , TEMP_ADDR         , CONFIG_FLAG_NONE     , "TEMP     " },
    { ANGLE_DEFAULT_Val                 , UANGLEA_ADDR      , CONFIG_FLAG_NONE     , "UANGLEA  " },
    { ANGLE_DEFAULT_Val                 , UANGLEB_ADDR      , CONFIG_FLAG_NONE     , "UANGLEB  " },
    { ANGLE_DEFAULT_Val                 , UANGLEC_ADDR      , CONFIG_FLAG_NONE     , "UANGLEC  " },
    // ATM90EXX_REGS_MET
    { ENERGY_DEFAULT_Val                , APENERGYT_ADDR    , CONFIG_FLAG_NONE     , "APENERGY " },
    { ENERGY_DEFAULT_Val                , APENERGYA_ADDR    , CONFIG_FLAG_NONE     , "APENERGYA" },
    { ENERGY_DEFAULT_Val                , APENERGYB_ADDR    , CONFIG_FLAG_NONE     , "APENERGYB" },
    { ENERGY_DEFAULT_Val                , APENERGYC_ADDR    , CONFIG_FLAG_NONE     , "APENERGYC" },
    { ENERGY_DEFAULT_Val                , ANENERGYT_ADDR    , CONFIG_FLAG_NONE     , "ANENERGY " },
    { ENERGY_DEFAULT_Val                , ANENERGYA_ADDR    , CONFIG_FLAG_NONE     , "ANENERGYA" },
    { ENERGY_DEFAULT_Val                , ANENERGYB_ADDR    , CONFIG_FLAG_NONE     , "ANENERGYB" },
    { ENERGY_DEFAULT_Val                , ANENERGYC_ADDR    , CONFIG_FLAG_NONE     , "ANENERGYC" },
    { ENERGY_DEFAULT_Val                , RPENERGYT_ADDR    , CONFIG_FLAG_NONE     , "RPENERGY " },
    { ENERGY_DEFAULT_Val                , RPENERGYA_ADDR    , CONFIG_FLAG_NONE     , "RPENERGYA" },
    { ENERGY_DEFAULT_Val                , RPENERGYB_ADDR    , CONFIG_FLAG_NONE     , "RPENERGYB" },
    { ENERGY_DEFAULT_Val                , RPENERGYC_ADDR    , CONFIG_FLAG_NONE     , "RPENERGYC" },
    { ENERGY_DEFAULT_Val                , RNENERGYT_ADDR    , CONFIG_FLAG_NONE     , "RNENERGY " },
    { ENERGY_DEFAULT_Val                , RNENERGYA_ADDR    , CONFIG_FLAG_NONE     , "RNENERGYA" },
    { ENERGY_DEFAULT_Val                , RNENERGYB_ADDR    , CONFIG_FLAG_NONE     , "RNENERGYB" },
    { ENERGY_DEFAULT_Val                , RNENERGYC_ADDR    , CONFIG_FLAG_NONE     , "RNENERGYC" },
    { ENERGY_DEFAULT_Val                , SAENERGYT_ADDR    , CONFIG_FLAG_NONE     , "SAENERGYT" },
    { ENERGY_DEFAULT_Val                , SENERGYA_ADDR     , CONFIG_FLAG_NONE     , "SENERGYA " },
    { ENERGY_DEFAULT_Val                , SENERGYB_ADDR     , CONFIG_FLAG_NONE     , "SENERGYB " },
    { ENERGY_DEFAULT_Val                , SENERGYC_ADDR     , CONFIG_FLAG_NONE     , "SENERGYC " },
    { ENERGY_DEFAULT_Val                , APENERGYTF_ADDR   , CONFIG_FLAG_NONE     , "APENERGYF" },
    { ENERGY_DEFAULT_Val                , APENERGYAF_ADDR   , CONFIG_FLAG_NONE     , "APENRGYAF" },
    { ENERGY_DEFAULT_Val                , APENERGYBF_ADDR   , CONFIG_FLAG_NONE     , "APENRGYBF" },
    { ENERGY_DEFAULT_Val                , APENERGYCF_ADDR   , CONFIG_FLAG_NONE     , "APENRGYCF" },
    { ENERGY_DEFAULT_Val                , ANENERGYTF_ADDR   , CONFIG_FLAG_NONE     , "ANENERGYF" },
    { ENERGY_DEFAULT_Val                , ANENERGYAF_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYAF" },
    { ENERGY_DEFAULT_Val                , ANENERGYBF_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYBF" },
    { ENERGY_DEFAULT_Val                , ANENERGYCF_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYCF" },
    { ENERGY_DEFAULT_Val                , APENERGYTH_ADDR   , CONFIG_FLAG_NONE     , "APENERGYH" },
    { ENERGY_DEFAULT_Val                , APENERGYAH_ADDR   , CONFIG_FLAG_NONE     , "APENRGYAH" },
    { ENERGY_DEFAULT_Val                , APENERGYBH_ADDR   , CONFIG_FLAG_NONE     , "APENRGYBH" },
    { ENERGY_DEFAULT_Val                , APENERGYCH_ADDR   , CONFIG_FLAG_NONE     , "APENRGYCH" },
    { ENERGY_DEFAULT_Val                , ANENERGYTH_ADDR   , CONFIG_FLAG_NONE     , "ANENERGYH" },
    { ENERGY_DEFAULT_Val                , ANENERGYAH_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYAH" },
    { ENERGY_DEFAULT_Val                , ANENERGYBH_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYBH" },
    { ENERGY_DEFAULT_Val                , ANENERGYCH_ADDR   , CONFIG_FLAG_NONE     , "ANENRGYCH" },
};

/*******************************************************************************
 End of File
 */
